In [1]:
# ReLU演算の確認

import numpy as np
# 2次元テンソル 行列
x = np.array([
    [12,3,6,14,7],
    [3,6,1,54,-67],
    [12,43,56,54,43],
])

print('shapeの確認\n', x.shape)

def native_relu(x):
    assert len(x.shape) == 2, ''
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

print('ReLU演算\n', native_relu(x))

shapeの確認
 (3, 5)
ReLU演算
 [[12  3  6 14  7]
 [ 3  6  1 54  0]
 [12 43 56 54 43]]


In [2]:
# 行列とベクトルの内積

# 行列(2次元テンソル)
x = np.array([
    [1,2,3],
    [3,6,1]
])

print(x.shape)
# ベクトル(1次元テンソル)
y = np.array([1,2,2])
print(y.shape)

z = np.dot(x,y)
print(z)

# ベクトル・行列の内積は求めることができない
# zr = np.dot(y,x)
# print(zr)

(2, 3)
(3,)
[11 17]


In [3]:
# 行列同士の内積

# 行列(2次元テンソル)
x = np.array([
    [1,2,3],
    [3,6,1]
])

y = np.array([
    [1,2],
    [3,6],
    [2,4]
])

z = np.dot(x,y)
print(z)

# 手での求め方は同じだが求めることはできない
# zr = x * y
# print(zr)

[[13 26]
 [23 46]]


In [4]:
# テンソルの変形
x = np.array([
    [0, 1],
    [2,3],
    [4,5]
])
print(x)
print(x.shape)

[[0 1]
 [2 3]
 [4 5]]
(3, 2)


In [5]:
x = x.reshape((6,1))
print(x)
print(x.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [6]:
# 転置行列の算出
x = np.array([
    [0, 1],
    [2,3],
    [4,5]
])
x = np.transpose(x)
print(x)
print(x.shape)

[[0 2 4]
 [1 3 5]]
(2, 3)
